import type { Question } from "@/lib/quiz/types";

// Quiz for the "Dividend Metrics: Payout, Coverage, and Yield Traps" lesson.
export const questions: Question[] = [
  {
    id: "dividend-metrics-in-depth.q1",
    lessonSlug: "dividend-metrics-in-depth",
    type: "numericChoice",
    difficulty: "easy",
    unit: "%",
    tags: ["dividends", "payout", "math"],
    prompt: "A company has net income of `$400M` and pays dividends of `$100M`. What is its payout ratio?",
    choices: [
      { id: "a", text: "25%" },
      { id: "b", text: "400%", feedback: "That divides the wrong way — payout is dividends ÷ net income." },
      { id: "c", text: "75%" },
      { id: "d", text: "4%" },
    ],
    correctId: "a",
    explanation: "`Payout ratio = dividends ÷ net income = 100 ÷ 400 = 25%`. The other 75% is retained.",
  },
  {
    id: "dividend-metrics-in-depth.q2",
    lessonSlug: "dividend-metrics-in-depth",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["dividends", "coverage", "math"],
    prompt: "A company has EPS of `$5` and pays a DPS of `$4`. What is its dividend coverage?",
    choices: [
      { id: "a", text: "0.8", feedback: "That's the payout ratio (DPS ÷ EPS) — coverage flips it: EPS ÷ DPS." },
      { id: "b", text: "1.25" },
      { id: "c", text: "20" },
      { id: "d", text: "9" },
    ],
    correctId: "b",
    explanation: "`Coverage = EPS ÷ DPS = 5 ÷ 4 = 1.25×`. Earnings cover the dividend 1.25 times — a thin cushion.",
  },
  {
    id: "dividend-metrics-in-depth.q3",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["dividends", "payout"],
    prompt: "A payout ratio **above 100%** means the company is…",
    choices: [
      { id: "a", text: "Retaining all of its profits" },
      { id: "b", text: "Paying out more than it earns, often funded by reserves or debt" },
      { id: "c", text: "Doubling its earnings" },
      { id: "d", text: "Paying no dividend at all" },
    ],
    correctId: "b",
    explanation: "Above 100% means dividends exceed net income — covered by **reserves or debt**, which is usually unsustainable.",
  },
  {
    id: "dividend-metrics-in-depth.q4",
    lessonSlug: "dividend-metrics-in-depth",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["dividends", "yield", "math"],
    prompt: "A stock pays an annual DPS of `$3` and trades at `$50`. What is its dividend yield?",
    choices: [
      { id: "a", text: "6%" },
      { id: "b", text: "16.7%", feedback: "That divides price by DPS — yield is DPS ÷ price." },
      { id: "c", text: "3%" },
      { id: "d", text: "150%" },
    ],
    correctId: "a",
    explanation: "`Dividend yield = DPS ÷ price = 3 ÷ 50 = 6%`.",
  },
  {
    id: "dividend-metrics-in-depth.q5",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "easy",
    tags: ["dividends", "fcf"],
    prompt: "Beyond net income, what should you check to confirm a dividend is sustainable?",
    choices: [
      { id: "a", text: "The company's free cash flow, since dividends are paid in cash" },
      { id: "b", text: "The CEO's salary" },
      { id: "c", text: "The number of employees" },
      { id: "d", text: "The trailing P/E only" },
    ],
    correctId: "a",
    explanation: "Dividends are paid in **cash**, so sanity-check against **free cash flow**. A healthy payout on accrual net income can still outrun the actual cash available.",
  },
  {
    id: "dividend-metrics-in-depth.q6",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "hard",
    tags: ["dividends", "scenario", "sustainability"],
    prompt: "A company has a payout ratio of `130%` and negative free cash flow, yet it keeps paying its dividend. What's the most likely situation?",
    choices: [
      { id: "a", text: "The dividend is rock-solid and likely to rise", feedback: "Paying more than you earn with no cash to back it is the opposite of solid." },
      { id: "b", text: "The dividend is funded by debt or reserves and a cut is likely" },
      { id: "c", text: "The company has unusually high earnings" },
      { id: "d", text: "Free cash flow is irrelevant to dividends" },
    ],
    correctId: "b",
    explanation: "Paying out 130% of earnings with negative FCF means the cash is coming from **debt or reserves** — not operations. That's unsustainable, and a cut is the likely outcome.",
  },
  {
    id: "dividend-metrics-in-depth.q7",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["dividends", "scenario", "yield-trap"],
    prompt: "A stock's dividend yield jumped from `3%` to `9%`, but the company never raised its dividend. What most likely happened?",
    choices: [
      { id: "a", text: "The share price fell sharply, mechanically lifting the yield" },
      { id: "b", text: "Earnings tripled" },
      { id: "c", text: "The company issued more shares" },
      { id: "d", text: "The dividend was tripled" },
    ],
    correctId: "a",
    explanation: "Yield = DPS ÷ price. With DPS unchanged, a yield jump from 3% to 9% means the **price fell sharply** — a classic yield-trap setup where the market expects a cut.",
  },
  {
    id: "dividend-metrics-in-depth.q8",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "hard",
    tags: ["dividends", "misconception", "yield-trap"],
    prompt: "Why is 'a higher dividend yield is always better' a misconception?",
    choices: [
      { id: "a", text: "Higher yields are taxed at 100%" },
      { id: "b", text: "A spiking yield is often a yield trap — the price fell on expectations of a cut" },
      { id: "c", text: "Dividends are never paid in cash" },
      { id: "d", text: "A high yield always means the company is growing" },
    ],
    correctId: "b",
    explanation: "An unusually high yield frequently signals trouble — the **price dropped** because the market anticipates a dividend cut. Sustainability matters more than the headline yield.",
  },
  {
    id: "dividend-metrics-in-depth.q9",
    lessonSlug: "dividend-metrics-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["dividends", "reit", "limits"],
    prompt: "A REIT has a payout ratio above 90%. Is that automatically a red flag?",
    choices: [
      { id: "a", text: "Yes — any payout above 90% always signals a coming cut" },
      { id: "b", text: "No — REITs must distribute most of their taxable income, so high payouts are normal for them" },
      { id: "c", text: "Yes — REITs are forbidden from paying dividends" },
      { id: "d", text: "No — because REITs never earn a profit" },
    ],
    correctId: "b",
    explanation: "REITs are required to distribute roughly **90%** of taxable income, so a 90%+ payout is *normal* by design — judge them differently from ordinary corporations.",
  },
];
