import type { Question } from "@/lib/quiz/types";

// Quiz for the "Earnings Reports: Beats, Misses, and Guidance" lesson.
export const questions: Question[] = [
  {
    id: "earnings-reports.q1",
    lessonSlug: "earnings-reports",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["earnings", "surprise", "math"],
    prompt: "Consensus EPS was `$2.00` and the company reported actual EPS of `$2.20`. What is the EPS surprise?",
    choices: [
      { id: "a", text: "+10%" },
      { id: "b", text: "+0.20%", feedback: "Express the $0.20 beat as a percentage of the $2.00 estimate: 0.20 ÷ 2.00 = 10%." },
      { id: "c", text: "+20%" },
      { id: "d", text: "+2%" },
    ],
    correctId: "a",
    explanation: "`Surprise = (actual − consensus) ÷ consensus = (2.20 − 2.00) ÷ 2.00 = +10%` — a beat.",
  },
  {
    id: "earnings-reports.q2",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "easy",
    tags: ["earnings", "guidance"],
    prompt: "What is 'guidance' in an earnings report?",
    choices: [
      { id: "a", text: "Management's own forecast for future periods" },
      { id: "b", text: "The analysts' average estimate", feedback: "That's the consensus estimate — guidance comes from management, not analysts." },
      { id: "c", text: "The historical revenue from last year" },
      { id: "d", text: "A regulator's required disclosure of risks" },
    ],
    correctId: "a",
    explanation: "**Guidance** is management's forward-looking forecast. Markets often react to it more than to the quarter just reported.",
  },
  {
    id: "earnings-reports.q3",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "medium",
    tags: ["earnings", "consensus"],
    prompt: "A company reports above the analyst consensus. This is called a…",
    choices: [
      { id: "a", text: "Miss" },
      { id: "b", text: "Beat" },
      { id: "c", text: "Drift" },
      { id: "d", text: "Sandbag" },
    ],
    correctId: "b",
    explanation: "Reporting **above** consensus is a **beat**; reporting below it is a **miss**. EPS and revenue each have their own consensus.",
  },
  {
    id: "earnings-reports.q4",
    lessonSlug: "earnings-reports",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["earnings", "surprise", "math"],
    prompt: "Consensus revenue was `$1,000M` but actual revenue came in at `$960M`. What is the revenue surprise?",
    choices: [
      { id: "a", text: "−4.0%" },
      { id: "b", text: "+4.0%", feedback: "Actual is below consensus, so the surprise is negative — a miss." },
      { id: "c", text: "−40%" },
      { id: "d", text: "−0.4%" },
    ],
    correctId: "a",
    explanation: "`Surprise = (960 − 1,000) ÷ 1,000 = −4.0%` — a revenue miss.",
  },
  {
    id: "earnings-reports.q5",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "medium",
    tags: ["earnings", "expectations"],
    prompt: "Why can a stock fall even after the company beats earnings?",
    choices: [
      { id: "a", text: "Stocks always fall on earnings day" },
      { id: "b", text: "Stocks move on the surprise versus expectations — a beat can still disappoint if guidance or revenue is weak" },
      { id: "c", text: "A beat legally forces a price drop" },
      { id: "d", text: "Beats only matter for bonds" },
    ],
    correctId: "b",
    explanation: "Price already reflects expectations. A 'good but not good enough' beat — especially with weak guidance or a revenue miss — can still send the stock down.",
  },
  {
    id: "earnings-reports.q6",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "hard",
    tags: ["earnings", "scenario", "guidance"],
    prompt: "A company beats on EPS but misses on revenue and cuts its guidance — and the stock drops `8%`. What's the soundest explanation?",
    choices: [
      { id: "a", text: "The market made an error that will reverse tomorrow" },
      { id: "b", text: "Forward expectations dominated — the revenue miss and lowered guidance outweighed the EPS beat" },
      { id: "c", text: "The EPS beat must have been fabricated" },
      { id: "d", text: "Dividends were cut" },
    ],
    correctId: "b",
    explanation: "Markets look forward. A **revenue miss plus cut guidance** signals weakening demand, which outweighs a backward-looking EPS beat — so the stock fell.",
  },
  {
    id: "earnings-reports.q7",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "hard",
    tags: ["earnings", "scenario", "buybacks"],
    prompt: "A company beats EPS, but net income was flat — the beat came entirely from share buybacks. How should you read it?",
    choices: [
      { id: "a", text: "A high-quality beat driven by strong demand" },
      { id: "b", text: "A lower-quality beat from financial engineering, since net income didn't grow" },
      { id: "c", text: "Proof revenue doubled" },
      { id: "d", text: "Evidence the dividend will rise" },
    ],
    correctId: "b",
    explanation: "Buybacks shrink the share count, lifting **EPS without raising net income**. That's a **lower-quality** beat — read *why* EPS rose before celebrating.",
  },
  {
    id: "earnings-reports.q8",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "medium",
    tags: ["earnings", "drift"],
    prompt: "What does 'post-earnings drift' describe?",
    choices: [
      { id: "a", text: "The tendency for a stock to keep moving in the surprise's direction for days afterward" },
      { id: "b", text: "The instant, one-time price jump at the report" },
      { id: "c", text: "Management changing its guidance mid-quarter" },
      { id: "d", text: "A regulator delaying the report" },
    ],
    correctId: "a",
    explanation: "Reactions aren't instantaneous. **Post-earnings drift** is the tendency for a stock to continue moving in the direction of the surprise over the following days.",
  },
  {
    id: "earnings-reports.q9",
    lessonSlug: "earnings-reports",
    type: "single",
    difficulty: "hard",
    tags: ["earnings", "sandbagging", "limits"],
    prompt: "What does it mean when a company's consensus estimate is 'sandbagged'?",
    choices: [
      { id: "a", text: "Expectations were set deliberately low, making a beat easy to deliver" },
      { id: "b", text: "The company refused to give any guidance" },
      { id: "c", text: "The estimate was inflated to scare investors" },
      { id: "d", text: "Revenue and EPS estimates were swapped" },
    ],
    correctId: "a",
    explanation: "**Sandbagging** means setting expectations low so the actual results easily clear them — making a 'beat' look more impressive than the underlying business is.",
  },
];
