import type { Question } from "@/lib/quiz/types";

// Quiz for the "Fundamental vs. Technical Analysis" lesson.
export const questions: Question[] = [
  {
    id: "fundamental-vs-technical-analysis.q1",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "easy",
    tags: ["analysis", "fundamental"],
    prompt: "What does **fundamental analysis** primarily study to value a security?",
    choices: [
      { id: "a", text: "Earnings, cash flow, assets, and the broader economy" },
      { id: "b", text: "Chart patterns and trading volume", feedback: "That's technical analysis — fundamental analysis looks at the business itself, not the chart." },
      { id: "c", text: "Only the stock's recent price trend" },
      { id: "d", text: "Whichever way the crowd is leaning today" },
    ],
    correctId: "a",
    explanation: "Fundamental analysis values a security from the **business and economy** — earnings, cash flow, assets, and growth — to estimate its **intrinsic value**.",
  },
  {
    id: "fundamental-vs-technical-analysis.q2",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "easy",
    tags: ["analysis", "technical"],
    prompt: "Which question does **technical analysis** mainly try to answer?",
    choices: [
      { id: "a", text: "What is the company's intrinsic value?" },
      { id: "b", text: "How much debt is on the balance sheet?" },
      { id: "c", text: "WHEN to act — based on price, volume, and trend" },
      { id: "d", text: "What dividend will the company pay next year?" },
    ],
    correctId: "c",
    explanation: "Technical analysis studies **price, volume, and charts** to read supply and demand — it's about **timing (WHEN to act)**, not about valuing the business.",
  },
  {
    id: "fundamental-vs-technical-analysis.q3",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "medium",
    tags: ["analysis", "assumptions", "technical"],
    prompt: "Which is a classic core assumption of **technical analysis**?",
    choices: [
      { id: "a", text: "Price always equals intrinsic value exactly" },
      { id: "b", text: "The market discounts everything — known information is already in the price" },
      { id: "c", text: "Earnings are the only thing that moves a stock" },
      { id: "d", text: "Charts are irrelevant once you know the cash flow", feedback: "That inverts the premise — technicals treat the chart as the key data, not an irrelevance." },
    ],
    correctId: "b",
    explanation: "Technical analysis classically assumes the **market discounts everything** (all known info is already in price), **prices move in trends**, and **history tends to repeat**.",
  },
  {
    id: "fundamental-vs-technical-analysis.q4",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "medium",
    tags: ["analysis", "fundamental", "assumptions"],
    prompt: "What core bet does **fundamental analysis** make about price?",
    choices: [
      { id: "a", text: "That price can drift away from intrinsic value, creating opportunity" },
      { id: "b", text: "That price never changes once set" },
      { id: "c", text: "That only the chart's trend matters" },
      { id: "d", text: "That volume drives all long-term returns" },
    ],
    correctId: "a",
    explanation: "Fundamental analysis bets that **price and value can diverge**, and that studying the business reveals that gap before the crowd prices it in.",
  },
  {
    id: "fundamental-vs-technical-analysis.q5",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "medium",
    tags: ["analysis", "use-cases"],
    prompt: "An investor wants to choose which companies to hold for several years. Which approach is **best suited** to that task?",
    choices: [
      { id: "a", text: "Technical analysis, because it times short-term entries" },
      { id: "b", text: "Neither — long-term selection can't be analyzed" },
      { id: "c", text: "Fundamental analysis, because it judges the business over a long horizon" },
      { id: "d", text: "Whichever method had the best chart last week", feedback: "Recent chart performance is a technical signal about timing, not a basis for long-term selection." },
    ],
    correctId: "c",
    explanation: "**Fundamental** analysis shines for **long-horizon selection** — deciding *what* to own. Technicals are better for shorter-term *timing*.",
  },
  {
    id: "fundamental-vs-technical-analysis.q6",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "medium",
    tags: ["analysis", "blend"],
    prompt: "How do many investors **blend** the two schools in practice?",
    choices: [
      { id: "a", text: "They use technicals to pick the business and fundamentals to draw the chart" },
      { id: "b", text: "They use fundamentals to build a shortlist, then technicals to time entries and exits" },
      { id: "c", text: "They alternate methods randomly each day" },
      { id: "d", text: "They ignore both and rely only on tips" },
    ],
    correctId: "b",
    explanation: "A common blend: **fundamentals** screen for businesses worth owning (*what*), then **technicals** help time the buy or sell (*when*). The two answer different questions.",
  },
  {
    id: "fundamental-vs-technical-analysis.q7",
    lessonSlug: "fundamental-vs-technical-analysis",
    type: "single",
    difficulty: "hard",
    tags: ["analysis", "misconception"],
    prompt: "Why is it a mistake to frame fundamental vs. technical analysis as 'rivals where one must be right'?",
    choices: [
      { id: "a", text: "Because technical analysis is illegal for retail investors" },
      { id: "b", text: "Because fundamental analysis only works in bear markets" },
      { id: "c", text: "Because they answer different questions — value (WHAT) vs. timing (WHEN) — and can be used together" },
      { id: "d", text: "Because both methods always give identical answers" },
    ],
    correctId: "c",
    explanation: "The two schools answer **different questions** — *what* to own vs. *when* to act. Choosing one is picking a **tool**, not declaring the other worthless; many investors blend them.",
  },
];
