import type { Question } from "@/lib/quiz/types";

// Quiz for the "Growth vs. Value: Two Investing Styles" lesson.
export const questions: Question[] = [
  {
    id: "growth-vs-value.q1",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "easy",
    tags: ["styles", "growth"],
    prompt: "Which set of traits best describes a classic **growth** stock?",
    choices: [
      { id: "a", text: "High P/E, fast revenue/earnings growth, little or no dividend" },
      { id: "b", text: "Low P/E, slow growth, a large dividend", feedback: "That describes a value stock, not a growth stock." },
      { id: "c", text: "No revenue and a low share price" },
      { id: "d", text: "Guaranteed returns with no risk" },
    ],
    correctId: "a",
    explanation: "Growth stocks combine **fast growth** with a **high multiple** and usually **little or no dividend**, because profits are reinvested.",
  },
  {
    id: "growth-vs-value.q2",
    lessonSlug: "growth-vs-value",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["styles", "peg", "math"],
    prompt: "Stock A has a P/E of `40` and growth of `20%`. Stock B has a P/E of `12` and growth of `4%`. Which has the lower PEG?",
    choices: [
      { id: "a", text: "Stock A, with a PEG of 2.0 (vs B's 3.0)" },
      { id: "b", text: "Stock B, with a PEG of 3.0", feedback: "B's PEG (12 ÷ 4 = 3.0) is higher than A's (40 ÷ 20 = 2.0)." },
      { id: "c", text: "They have equal PEGs" },
      { id: "d", text: "Stock B, with a PEG of 0.33" },
    ],
    correctId: "a",
    explanation: "`A PEG = 40 ÷ 20 = 2.0`; `B PEG = 12 ÷ 4 = 3.0`. Despite a much higher P/E, **Stock A** has the lower PEG once growth is accounted for.",
  },
  {
    id: "growth-vs-value.q3",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "medium",
    tags: ["styles", "value"],
    prompt: "What is the core bet behind buying a **value** stock?",
    choices: [
      { id: "a", text: "That the market is underpricing a fundamentally sound business" },
      { id: "b", text: "That earnings will grow 50% per year" },
      { id: "c", text: "That the stock will never pay a dividend" },
      { id: "d", text: "That the multiple will keep expanding forever" },
    ],
    correctId: "a",
    explanation: "Value investing bets the market has **underpriced** a sound business — buying it cheap relative to fundamentals, often while collecting a dividend.",
  },
  {
    id: "growth-vs-value.q4",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "medium",
    tags: ["styles", "peg"],
    prompt: "How does the PEG ratio 'bridge' growth and value styles?",
    choices: [
      { id: "a", text: "It asks whether a high P/E is justified by the growth behind it" },
      { id: "b", text: "It ignores both P/E and growth" },
      { id: "c", text: "It measures the dividend yield" },
      { id: "d", text: "It only works for value stocks" },
    ],
    correctId: "a",
    explanation: "PEG = `P/E ÷ growth`, so it directly tests whether a rich multiple is **warranted by growth** — letting you compare a fast grower against a cheap stalwart.",
  },
  {
    id: "growth-vs-value.q5",
    lessonSlug: "growth-vs-value",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["styles", "peg", "math"],
    prompt: "Value Co trades at `$30` with EPS of `$3` and expected growth of `4%`. What is its PEG?",
    choices: [
      { id: "a", text: "2.5" },
      { id: "b", text: "10", feedback: "That's the P/E (30 ÷ 3) — PEG divides the P/E by the 4% growth rate." },
      { id: "c", text: "0.4" },
      { id: "d", text: "1.2" },
    ],
    correctId: "a",
    explanation: "`P/E = 30 ÷ 3 = 10`. `PEG = 10 ÷ 4 = 2.5`. A low P/E with tiny growth still yields a high PEG.",
  },
  {
    id: "growth-vs-value.q6",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "medium",
    tags: ["styles", "rotation"],
    prompt: "When do value stocks tend to outperform growth stocks?",
    choices: [
      { id: "a", text: "Always — value wins in every environment" },
      { id: "b", text: "Often when interest rates rise and high-growth names re-price" },
      { id: "c", text: "Only during recessions, never otherwise" },
      { id: "d", text: "Never — growth always wins" },
    ],
    correctId: "b",
    explanation: "Neither style wins permanently. Value tends to do better when **rates rise** and richly priced growth stocks re-price; growth tends to lead in low-rate expansions.",
  },
  {
    id: "growth-vs-value.q7",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "hard",
    tags: ["styles", "scenario", "de-rating"],
    prompt: "A company's growth slows from `35%` to `8%`, and its P/E falls from `60` to `20` even though earnings actually rose. What happened?",
    choices: [
      { id: "a", text: "Multiple compression (de-rating) — the market repriced the slower growth" },
      { id: "b", text: "The company became a guaranteed value bargain" },
      { id: "c", text: "Earnings must have collapsed" },
      { id: "d", text: "The dividend was raised sharply" },
    ],
    correctId: "a",
    explanation: "When growth fades, the market pays a **lower multiple** for the same earnings — **de-rating** (multiple compression). The stock can fall even as earnings rise.",
  },
  {
    id: "growth-vs-value.q8",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "medium",
    tags: ["styles", "scenario", "value-trap"],
    prompt: "An investor simply buys the lowest-P/E stock in a sector. What key risk are they ignoring?",
    choices: [
      { id: "a", text: "Value-trap risk — the low P/E may reflect a deteriorating business" },
      { id: "b", text: "That low-P/E stocks are illegal to own" },
      { id: "c", text: "That the dividend is always cut" },
      { id: "d", text: "There is no risk in buying the cheapest stock" },
    ],
    correctId: "a",
    explanation: "The cheapest multiple can be cheap *for a reason* — a **value trap** where prospects are deteriorating. Low P/E alone is not a buy signal.",
  },
  {
    id: "growth-vs-value.q9",
    lessonSlug: "growth-vs-value",
    type: "single",
    difficulty: "hard",
    tags: ["styles", "misconception", "peg"],
    prompt: "Growth Co has a P/E of `50` and PEG of `1.67`; Value Co has a P/E of `10` and PEG of `2.5`. Why is 'the low-P/E stock is the better value' wrong here?",
    choices: [
      { id: "a", text: "Because P/E is irrelevant to valuation" },
      { id: "b", text: "Because Value Co's higher PEG shows its low growth makes it pricier on a growth-adjusted basis" },
      { id: "c", text: "Because Growth Co pays a bigger dividend" },
      { id: "d", text: "Because a lower P/E is always the better deal" },
    ],
    correctId: "b",
    explanation: "Value Co's P/E is lower, but its **PEG is higher** (2.5 vs 1.67) because growth is so slow. Adjusted for growth, the 'cheap' stock is actually more expensive — a lower multiple isn't automatically a better deal.",
  },
];
