import type { Question } from "@/lib/quiz/types";

// Quiz for the "Liquidity and Solvency Ratios" lesson.
export const questions: Question[] = [
  {
    id: "liquidity-and-solvency-ratios.q1",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "numericChoice",
    difficulty: "easy",
    tags: ["liquidity", "current-ratio", "math"],
    prompt: "Current assets are `$300M` and current liabilities are `$200M`. What is the current ratio?",
    choices: [
      { id: "a", text: "0.67", feedback: "That divides liabilities by assets — the current ratio is current assets ÷ current liabilities." },
      { id: "b", text: "1.5" },
      { id: "c", text: "100" },
      { id: "d", text: "500" },
    ],
    correctId: "b",
    explanation: "`Current ratio = current assets ÷ current liabilities = 300 ÷ 200 = 1.5`.",
  },
  {
    id: "liquidity-and-solvency-ratios.q2",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "numericChoice",
    difficulty: "medium",
    tags: ["liquidity", "quick-ratio", "math"],
    prompt: "Current assets are `$400M`, of which inventory is `$150M`, and current liabilities are `$200M`. What is the quick (acid-test) ratio?",
    choices: [
      { id: "a", text: "2.0", feedback: "That's the current ratio — the quick ratio first subtracts inventory from current assets." },
      { id: "b", text: "0.75" },
      { id: "c", text: "1.25" },
      { id: "d", text: "2.75" },
    ],
    correctId: "c",
    explanation: "`Quick ratio = (current assets − inventory) ÷ current liabilities = (400 − 150) ÷ 200 = 250 ÷ 200 = 1.25`.",
  },
  {
    id: "liquidity-and-solvency-ratios.q3",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "single",
    difficulty: "easy",
    tags: ["liquidity", "quick-ratio", "concept"],
    prompt: "How does the quick ratio differ from the current ratio?",
    choices: [
      { id: "a", text: "It adds long-term debt to the denominator" },
      { id: "b", text: "It excludes inventory from current assets, making it a stricter test" },
      { id: "c", text: "It uses EBIT instead of current assets" },
      { id: "d", text: "It divides by shareholders' equity instead of current liabilities" },
    ],
    correctId: "b",
    explanation: "The quick (acid-test) ratio strips out inventory — the slowest current asset to turn into cash — so it is a more conservative liquidity test than the current ratio.",
  },
  {
    id: "liquidity-and-solvency-ratios.q4",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "numericChoice",
    difficulty: "medium",
    tags: ["solvency", "interest-coverage", "math"],
    prompt: "EBIT is `$180M` and interest expense is `$60M`. What is the interest coverage ratio?",
    choices: [
      { id: "a", text: "0.33", feedback: "That divides interest by EBIT — coverage is EBIT ÷ interest expense." },
      { id: "b", text: "120" },
      { id: "c", text: "240" },
      { id: "d", text: "3.0" },
    ],
    correctId: "d",
    explanation: "`Interest coverage = EBIT ÷ interest expense = 180 ÷ 60 = 3.0` — operating profit covers the interest bill three times over.",
  },
  {
    id: "liquidity-and-solvency-ratios.q5",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "numericChoice",
    difficulty: "medium",
    tags: ["solvency", "debt-to-equity", "math"],
    prompt: "Total liabilities are `$600M` and shareholders' equity is `$500M`. What is the debt-to-equity ratio?",
    choices: [
      { id: "a", text: "1.2" },
      { id: "b", text: "0.83", feedback: "That divides equity by liabilities — D/E is total liabilities ÷ shareholders' equity." },
      { id: "c", text: "1100" },
      { id: "d", text: "100" },
    ],
    correctId: "a",
    explanation: "`Debt-to-equity = total liabilities ÷ shareholders' equity = 600 ÷ 500 = 1.2` — modestly more debt than equity.",
  },
  {
    id: "liquidity-and-solvency-ratios.q6",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "single",
    difficulty: "medium",
    tags: ["liquidity", "solvency", "concept"],
    prompt: "Which pairing correctly matches each ratio to what it measures?",
    choices: [
      { id: "a", text: "Current ratio measures long-term debt; interest coverage measures short-term bills" },
      { id: "b", text: "Both the current ratio and debt-to-equity measure the same thing" },
      { id: "c", text: "The current ratio measures short-term liquidity; debt-to-equity measures long-term solvency" },
      { id: "d", text: "Interest coverage measures liquidity; the quick ratio measures solvency" },
    ],
    correctId: "c",
    explanation: "Liquidity ratios (current, quick) test whether the firm can pay bills due within a year; solvency/leverage ratios (D/E, interest coverage) test whether it can carry long-term debt.",
  },
  {
    id: "liquidity-and-solvency-ratios.q7",
    lessonSlug: "liquidity-and-solvency-ratios",
    type: "single",
    difficulty: "hard",
    tags: ["liquidity", "scenario", "inventory"],
    prompt: "A retailer shows a current ratio of `2.0` but a quick ratio of `0.6`. What does the gap most likely indicate?",
    choices: [
      { id: "a", text: "The company has negative shareholders' equity" },
      { id: "b", text: "Much of its current assets are inventory it still has to sell to raise cash" },
      { id: "c", text: "Its interest coverage must be below 1" },
      { id: "d", text: "It has no current liabilities" },
    ],
    correctId: "b",
    explanation: "The gap between the two ratios *is* the inventory effect. A high current ratio paired with a low quick ratio means the firm is leaning on inventory it hasn't yet converted to cash — a warning the current ratio alone would hide.",
  },
];
