import type { Question } from "@/lib/quiz/types";

// Quiz for the "Margins and ROE: Measuring Profitability" lesson.
export const questions: Question[] = [
  {
    id: "margins-and-roe.q1",
    lessonSlug: "margins-and-roe",
    type: "numericChoice",
    difficulty: "easy",
    unit: "%",
    tags: ["profitability", "margins", "math"],
    prompt: "Operating income is `$90M` on revenue of `$600M`. What is the operating margin?",
    choices: [
      { id: "a", text: "15%" },
      { id: "b", text: "6.67%", feedback: "That divides revenue by operating income — margin is operating income ÷ revenue." },
      { id: "c", text: "90%" },
      { id: "d", text: "54%" },
    ],
    correctId: "a",
    explanation: "`Operating margin = operating income ÷ revenue = 90 ÷ 600 = 15%`.",
  },
  {
    id: "margins-and-roe.q2",
    lessonSlug: "margins-and-roe",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["profitability", "roe", "math"],
    prompt: "Net income is `$50M` and shareholders' equity is `$250M`. What is the ROE?",
    choices: [
      { id: "a", text: "5%", feedback: "Check the divisor — ROE is net income ÷ equity, here 50 ÷ 250." },
      { id: "b", text: "20%" },
      { id: "c", text: "500%" },
      { id: "d", text: "25%" },
    ],
    correctId: "b",
    explanation: "`ROE = net income ÷ equity = 50 ÷ 250 = 20%` — each dollar of equity earned $0.20 of profit.",
  },
  {
    id: "margins-and-roe.q3",
    lessonSlug: "margins-and-roe",
    type: "single",
    difficulty: "medium",
    tags: ["profitability", "margins"],
    prompt: "Which ordering of margins is always true?",
    choices: [
      { id: "a", text: "Net ≥ operating ≥ gross", feedback: "It's the reverse — each lower margin subtracts more costs." },
      { id: "b", text: "Gross ≥ operating ≥ net" },
      { id: "c", text: "Operating ≥ gross ≥ net" },
      { id: "d", text: "They are always equal" },
    ],
    correctId: "b",
    explanation: "Each step subtracts more costs, so **gross ≥ operating ≥ net** always holds.",
  },
  {
    id: "margins-and-roe.q4",
    lessonSlug: "margins-and-roe",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["profitability", "margins", "math"],
    prompt: "Revenue is `$1,000M` and COGS is `$600M`. What is the gross margin?",
    choices: [
      { id: "a", text: "40%" },
      { id: "b", text: "60%", feedback: "That's the COGS as a share of revenue — gross margin is gross profit ÷ revenue." },
      { id: "c", text: "166%" },
      { id: "d", text: "400%" },
    ],
    correctId: "a",
    explanation: "`Gross profit = 1,000 − 600 = 400`. `Gross margin = 400 ÷ 1,000 = 40%`.",
  },
  {
    id: "margins-and-roe.q5",
    lessonSlug: "margins-and-roe",
    type: "single",
    difficulty: "easy",
    tags: ["profitability", "roe"],
    prompt: "What does ROE measure?",
    choices: [
      { id: "a", text: "Profit generated per dollar of shareholders' equity" },
      { id: "b", text: "Revenue per employee" },
      { id: "c", text: "The dividend paid per share" },
      { id: "d", text: "The share price divided by earnings" },
    ],
    correctId: "a",
    explanation: "`ROE = net income ÷ shareholders' equity` — how much profit the company squeezes from each dollar of equity.",
  },
  {
    id: "margins-and-roe.q6",
    lessonSlug: "margins-and-roe",
    type: "single",
    difficulty: "hard",
    tags: ["profitability", "scenario", "leverage"],
    prompt: "Firms A and B both show an `18%` ROE. A uses little debt; B's ROE rests on debt-funded buybacks that shrank its equity. Which is the higher-quality result?",
    choices: [
      { id: "a", text: "Firm A, because its ROE comes from operations rather than leverage" },
      { id: "b", text: "Firm B, because debt always improves a company" },
      { id: "c", text: "They are identical in quality since the ROE is equal" },
      { id: "d", text: "Neither — ROE never reflects quality" },
    ],
    correctId: "a",
    explanation: "B's ROE is inflated by **leverage**: buybacks shrank equity, lifting the ratio without better operations. **Firm A's** operations-driven 18% is the higher-quality result.",
  },
  {
    id: "margins-and-roe.q7",
    lessonSlug: "margins-and-roe",
    type: "single",
    difficulty: "medium",
    tags: ["profitability", "scenario", "industry"],
    prompt: "A software firm has a `35%` net margin; a grocery chain has a `2%` net margin. Is the grocer poorly run?",
    choices: [
      { id: "a", text: "Yes — any margin under 10% means bad management" },
      { id: "b", text: "Not necessarily — margins are industry-specific, and groceries are inherently thin-margin" },
      { id: "c", text: "Yes — software margins are the universal benchmark" },
      { id: "d", text: "No — because grocers don't have costs" },
    ],
    correctId: "b",
    explanation: "'Good' is **industry-relative**. Groceries run on thin margins by nature; software runs high. Compare each company to its *own* industry, not across industries.",
  },
  {
    id: "margins-and-roe.q8",
    lessonSlug: "margins-and-roe",
    type: "single",
    difficulty: "hard",
    tags: ["profitability", "misconception", "leverage"],
    prompt: "Why is 'higher ROE always means a better-run company' a misconception?",
    choices: [
      { id: "a", text: "ROE is unrelated to profit" },
      { id: "b", text: "ROE can be propped up by debt and buybacks that shrink the equity base" },
      { id: "c", text: "ROE only applies to unprofitable firms" },
      { id: "d", text: "ROE ignores net income" },
    ],
    correctId: "b",
    explanation: "Debt-funded buybacks shrink equity, mechanically boosting ROE without any operational gain. Check **leverage** (e.g., via DuPont) before crediting management.",
  },
  {
    id: "margins-and-roe.q9",
    lessonSlug: "margins-and-roe",
    type: "numericChoice",
    difficulty: "medium",
    unit: "%",
    tags: ["profitability", "margins", "math"],
    prompt: "Net income is `$120M` on revenue of `$1,000M`. What is the net margin?",
    choices: [
      { id: "a", text: "12%" },
      { id: "b", text: "8.3%", feedback: "That divides revenue by net income — net margin is net income ÷ revenue." },
      { id: "c", text: "120%" },
      { id: "d", text: "20%" },
    ],
    correctId: "a",
    explanation: "`Net margin = net income ÷ revenue = 120 ÷ 1,000 = 12%`.",
  },
];
