import type { Question } from "@/lib/quiz/types";

// Quiz for the "P/B and P/S: Valuing Assets and Sales" lesson.
export const questions: Question[] = [
  {
    id: "pb-and-ps-ratios.q1",
    lessonSlug: "pb-and-ps-ratios",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["valuation", "pb", "math"],
    prompt: "A company has equity of `$500M`, `50M` shares outstanding, and trades at `$30`. What is its P/B ratio?",
    choices: [
      { id: "a", text: "3.0" },
      { id: "b", text: "10", feedback: "That's the book value per share (500 ÷ 50), not the P/B — divide price by it." },
      { id: "c", text: "0.33" },
      { id: "d", text: "15" },
    ],
    correctId: "a",
    explanation: "`Book value per share = 500 ÷ 50 = $10`. `P/B = price ÷ BVPS = 30 ÷ 10 = 3.0`.",
  },
  {
    id: "pb-and-ps-ratios.q2",
    lessonSlug: "pb-and-ps-ratios",
    type: "numericChoice",
    difficulty: "easy",
    unit: "x",
    tags: ["valuation", "ps", "math"],
    prompt: "A company has a market cap of `$6,000M` and revenue of `$2,000M`. What is its P/S ratio?",
    choices: [
      { id: "a", text: "3.0" },
      { id: "b", text: "0.33", feedback: "That divides the wrong way — P/S is market cap ÷ revenue." },
      { id: "c", text: "12,000" },
      { id: "d", text: "4,000" },
    ],
    correctId: "a",
    explanation: "`P/S = market cap ÷ revenue = 6,000 ÷ 2,000 = 3.0`.",
  },
  {
    id: "pb-and-ps-ratios.q3",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "medium",
    tags: ["valuation", "pb"],
    prompt: "For which type of company is the P/B ratio most useful?",
    choices: [
      { id: "a", text: "Asset-heavy firms like banks, insurers, and REITs" },
      { id: "b", text: "Asset-light software firms", feedback: "Software value lives in intangibles off the balance sheet, distorting P/B." },
      { id: "c", text: "Companies with no revenue" },
      { id: "d", text: "Companies that pay no dividend" },
    ],
    correctId: "a",
    explanation: "P/B compares price to balance-sheet net worth, so it fits **asset-heavy** businesses — banks, insurers, REITs — whose value sits in tangible assets.",
  },
  {
    id: "pb-and-ps-ratios.q4",
    lessonSlug: "pb-and-ps-ratios",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["valuation", "pb", "math"],
    prompt: "Total assets are `$2,000M`, total liabilities `$1,400M`, and there are `100M` shares. What is the book value per share?",
    choices: [
      { id: "a", text: "$34", feedback: "That subtracts shares incorrectly — first find equity, then divide by shares." },
      { id: "b", text: "$6" },
      { id: "c", text: "$20" },
      { id: "d", text: "$14" },
    ],
    correctId: "b",
    explanation: "`Equity = 2,000 − 1,400 = $600M`. `Book value per share = 600 ÷ 100 = $6`.",
  },
  {
    id: "pb-and-ps-ratios.q5",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "easy",
    tags: ["valuation", "ps"],
    prompt: "Why is the P/S ratio especially useful for early-stage companies?",
    choices: [
      { id: "a", text: "It requires no earnings, so it still works when a company is unprofitable" },
      { id: "b", text: "It always shows the company is undervalued" },
      { id: "c", text: "It measures dividend safety" },
      { id: "d", text: "It ignores the share price" },
    ],
    correctId: "a",
    explanation: "P/S uses revenue, not profit, so it remains meaningful for **unprofitable or early-stage** firms (and cyclicals) where P/E fails.",
  },
  {
    id: "pb-and-ps-ratios.q6",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "scenario", "ps"],
    prompt: "An early-stage software company has no profits and few tangible assets. Which valuation ratio fits best?",
    choices: [
      { id: "a", text: "P/E, since earnings are the gold standard", feedback: "P/E needs positive earnings, which this company lacks." },
      { id: "b", text: "P/S, because it works without earnings" },
      { id: "c", text: "P/B, because software is asset-heavy", feedback: "Software is asset-light — its value lives in intangibles, distorting P/B." },
      { id: "d", text: "Dividend yield" },
    ],
    correctId: "b",
    explanation: "With no profits, P/E breaks; with few tangible assets, P/B is distorted. **P/S** still works because it only needs revenue.",
  },
  {
    id: "pb-and-ps-ratios.q7",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "medium",
    tags: ["valuation", "scenario", "pb"],
    prompt: "A retailer trades at a P/B of `0.7` while its closest peer trades at `2.5`. What's the soundest next step?",
    choices: [
      { id: "a", text: "Buy immediately — a P/B below 1 is always a bargain", feedback: "P/B below 1 can signal impending write-downs, not a deal — investigate first." },
      { id: "b", text: "Investigate whether the assets face impairment before assuming it's cheap" },
      { id: "c", text: "Conclude the peer is fraudulent" },
      { id: "d", text: "Ignore P/B and rely only on dividend yield" },
    ],
    correctId: "b",
    explanation: "A P/B of `0.7` may be a bargain or a warning that book value is about to be written down (**impairment**). Investigate the *why* before concluding it's cheap.",
  },
  {
    id: "pb-and-ps-ratios.q8",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "misconception", "ps"],
    prompt: "What's the main blind spot of the P/S ratio?",
    choices: [
      { id: "a", text: "It overstates the share price" },
      { id: "b", text: "It ignores profitability, so a high-revenue money-loser can look 'cheap'" },
      { id: "c", text: "It only works for banks" },
      { id: "d", text: "It cannot be computed without dividends" },
    ],
    correctId: "b",
    explanation: "P/S says nothing about whether sales turn into profit. A company with big revenue but big losses can appear cheap on P/S — always pair it with margins.",
  },
  {
    id: "pb-and-ps-ratios.q9",
    lessonSlug: "pb-and-ps-ratios",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "pb", "limits"],
    prompt: "Why does P/B often look absurdly high for asset-light companies like software firms?",
    choices: [
      { id: "a", text: "Their revenue is always negative" },
      { id: "b", text: "Much of their value is intangible and sits off the balance sheet, shrinking book value" },
      { id: "c", text: "They never have any liabilities" },
      { id: "d", text: "Their shares outstanding are unusually low" },
    ],
    correctId: "b",
    explanation: "Brands, code, and know-how rarely appear on the balance sheet, so book value is tiny relative to price. That makes **P/B inflated** for asset-light firms even when they're excellent businesses.",
  },
];
