import type { Question } from "@/lib/quiz/types";

// Quiz for the "P/E Ratio in Depth: Trailing, Forward, and PEG" lesson.
export const questions: Question[] = [
  {
    id: "pe-ratio-in-depth.q1",
    lessonSlug: "pe-ratio-in-depth",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["valuation", "peg", "math"],
    prompt: "A stock has a P/E of `30` and expected earnings growth of `20%`. What is its PEG ratio?",
    choices: [
      { id: "a", text: "0.67", feedback: "That divides growth by P/E — PEG is P/E divided by the growth rate." },
      { id: "b", text: "1.5" },
      { id: "c", text: "10" },
      { id: "d", text: "600" },
    ],
    correctId: "b",
    explanation: "`PEG = P/E ÷ growth rate = 30 ÷ 20 = 1.5`. Above 1 hints the stock may be overvalued relative to its growth.",
  },
  {
    id: "pe-ratio-in-depth.q2",
    lessonSlug: "pe-ratio-in-depth",
    type: "numericChoice",
    difficulty: "easy",
    unit: "x",
    tags: ["valuation", "forward-pe", "math"],
    prompt: "A stock trades at `$48` with a forward (projected) EPS of `$4`. What is its forward P/E?",
    choices: [
      { id: "a", text: "12" },
      { id: "b", text: "192", feedback: "That multiplies — forward P/E is price divided by forward EPS." },
      { id: "c", text: "44" },
      { id: "d", text: "0.08" },
    ],
    correctId: "a",
    explanation: "`Forward P/E = price ÷ forward EPS = 48 ÷ 4 = 12`.",
  },
  {
    id: "pe-ratio-in-depth.q3",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["valuation", "trailing-forward"],
    prompt: "What is the key difference between trailing and forward P/E?",
    choices: [
      { id: "a", text: "Trailing uses the share price; forward uses market cap" },
      { id: "b", text: "Trailing uses last-12-months actual EPS; forward uses projected next-12-months EPS" },
      { id: "c", text: "Trailing is always higher than forward" },
      { id: "d", text: "Forward P/E ignores the share price" },
    ],
    correctId: "b",
    explanation: "**Trailing P/E** uses actual reported EPS over the past year; **forward P/E** uses *estimated* EPS for the next year — accurate only if the estimate holds.",
  },
  {
    id: "pe-ratio-in-depth.q4",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["valuation", "peg"],
    prompt: "As a rough heuristic, a PEG ratio **below 1** suggests a stock is…",
    choices: [
      { id: "a", text: "Possibly undervalued relative to its growth" },
      { id: "b", text: "Definitely overvalued", feedback: "A PEG above 1, not below, leans toward overvalued." },
      { id: "c", text: "Unprofitable" },
      { id: "d", text: "Paying a high dividend" },
    ],
    correctId: "a",
    explanation: "PEG ≈ 1 is roughly fair; **below 1** may be undervalued; above 1 may be overvalued. It's a heuristic, not a verdict.",
  },
  {
    id: "pe-ratio-in-depth.q5",
    lessonSlug: "pe-ratio-in-depth",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["valuation", "trailing-pe", "math"],
    prompt: "A stock trades at `$60` with trailing EPS of `$3`. What is its trailing P/E?",
    choices: [
      { id: "a", text: "20" },
      { id: "b", text: "180", feedback: "That multiplies — P/E divides price by EPS." },
      { id: "c", text: "0.05" },
      { id: "d", text: "57" },
    ],
    correctId: "a",
    explanation: "`Trailing P/E = price ÷ trailing EPS = 60 ÷ 3 = 20`.",
  },
  {
    id: "pe-ratio-in-depth.q6",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "scenario", "limits"],
    prompt: "A company posted a **net loss** last quarter, so its trailing P/E shows N/A. What's the best valuation workaround?",
    choices: [
      { id: "a", text: "Use a forward P/E (on expected positive earnings) or a price-to-sales ratio" },
      { id: "b", text: "Assume the P/E is zero" },
      { id: "c", text: "Treat the negative trailing P/E as a buy signal", feedback: "A negative P/E is meaningless, not a signal — switch to a metric that still works." },
      { id: "d", text: "Conclude the stock cannot be valued at all" },
    ],
    correctId: "a",
    explanation: "With negative earnings, P/E breaks down. Investors switch to a **forward P/E** (if profits are expected to return) or to **P/S**, which doesn't depend on positive earnings.",
  },
  {
    id: "pe-ratio-in-depth.q7",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "medium",
    tags: ["valuation", "scenario", "trailing-forward"],
    prompt: "A stock's trailing P/E is `25` but its forward P/E is `15`. What does the market most likely expect?",
    choices: [
      { id: "a", text: "EPS to grow over the next year" },
      { id: "b", text: "EPS to decline over the next year", feedback: "Falling earnings would push the forward P/E *above* trailing, not below." },
      { id: "c", text: "The dividend to be cut" },
      { id: "d", text: "The share price to fall sharply" },
    ],
    correctId: "a",
    explanation: "A forward P/E *below* trailing means earnings are expected to **rise** — growing EPS shrinks the forward multiple.",
  },
  {
    id: "pe-ratio-in-depth.q8",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "misconception", "value-trap"],
    prompt: "Why is 'a low P/E always means cheap' a misconception?",
    choices: [
      { id: "a", text: "A low P/E is mathematically impossible" },
      { id: "b", text: "A low P/E can reflect declining prospects — a value trap, not a bargain" },
      { id: "c", text: "Low P/E stocks never pay dividends" },
      { id: "d", text: "Low P/E only applies to bonds" },
    ],
    correctId: "b",
    explanation: "Cheap and *cheap for a reason* look identical on one number. A low P/E often signals the market expects earnings to fall — a **value trap** — while a high P/E can be justified by growth.",
  },
  {
    id: "pe-ratio-in-depth.q9",
    lessonSlug: "pe-ratio-in-depth",
    type: "single",
    difficulty: "hard",
    tags: ["valuation", "peg", "limits"],
    prompt: "Why does the PEG ratio break down for a company with very low growth?",
    choices: [
      { id: "a", text: "The P/E becomes negative" },
      { id: "b", text: "A tiny growth-rate denominator makes PEG explode to a meaningless number" },
      { id: "c", text: "Low-growth companies have no share price" },
      { id: "d", text: "PEG ignores the P/E entirely" },
    ],
    correctId: "b",
    explanation: "PEG divides by the growth rate. With near-zero growth, that denominator shrinks and PEG balloons, making the ratio useless for slow growers.",
  },
];
