import type { Question } from "@/lib/quiz/types";

// Quiz for the "The Cash Flow Statement: Why Cash ≠ Profit" lesson.
export const questions: Question[] = [
  {
    id: "the-cash-flow-statement.q1",
    lessonSlug: "the-cash-flow-statement",
    type: "numericChoice",
    difficulty: "easy",
    unit: "$",
    tags: ["fundamentals", "cash-flow", "math"],
    prompt: "Operating cash flow is `$200M` and capex is `$70M`. What is free cash flow?",
    choices: [
      { id: "a", text: "$270M", feedback: "FCF subtracts capex from operating cash flow, not adds it." },
      { id: "b", text: "$130M" },
      { id: "c", text: "$70M" },
      { id: "d", text: "$200M" },
    ],
    correctId: "b",
    explanation: "`FCF = operating cash flow − capex = 200 − 70 = $130M` — the cash left after keeping the business running.",
  },
  {
    id: "the-cash-flow-statement.q2",
    lessonSlug: "the-cash-flow-statement",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["fundamentals", "cash-flow", "math"],
    prompt: "Net income is `$80M`, depreciation is `$25M`, and inventory rose `$15M`. What is operating cash flow (CFO)?",
    choices: [
      { id: "a", text: "$120M", feedback: "The inventory increase ties up cash and should be subtracted, not added." },
      { id: "b", text: "$90M" },
      { id: "c", text: "$70M" },
      { id: "d", text: "$105M" },
    ],
    correctId: "b",
    explanation: "Start at net income `$80M`, add back depreciation `+$25M`, subtract the inventory increase `−$15M`: `80 + 25 − 15 = $90M`.",
  },
  {
    id: "the-cash-flow-statement.q3",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "easy",
    tags: ["fundamentals", "cash-flow"],
    prompt: "Capital expenditures (capex) appear in which section of the cash flow statement?",
    choices: [
      { id: "a", text: "Operating activities", feedback: "Capex is spending on long-term assets, which belongs in investing." },
      { id: "b", text: "Investing activities" },
      { id: "c", text: "Financing activities" },
      { id: "d", text: "It is not on the cash flow statement" },
    ],
    correctId: "b",
    explanation: "Capex is cash spent on long-term assets like plants and equipment, so it sits in the **investing activities** section.",
  },
  {
    id: "the-cash-flow-statement.q4",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "cash-flow"],
    prompt: "When reconciling net income to CFO, how is depreciation treated?",
    choices: [
      { id: "a", text: "Subtracted, because it is an expense" },
      { id: "b", text: "Added back, because it reduced profit but used no cash" },
      { id: "c", text: "Ignored entirely" },
      { id: "d", text: "Added to capex" },
    ],
    correctId: "b",
    explanation: "Depreciation is a **non-cash charge** — it lowered net income but no cash left the business, so it is *added back* when computing CFO.",
  },
  {
    id: "the-cash-flow-statement.q5",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "cash-flow"],
    prompt: "Which financial moves belong in the **financing** activities section?",
    choices: [
      { id: "a", text: "Buying new equipment" },
      { id: "b", text: "Issuing debt or equity, paying dividends, and buying back shares" },
      { id: "c", text: "Collecting cash from customers" },
      { id: "d", text: "Paying suppliers for inventory" },
    ],
    correctId: "b",
    explanation: "Financing activities cover cash flows with lenders and owners: **debt, equity, dividends, and buybacks**.",
  },
  {
    id: "the-cash-flow-statement.q6",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "cash-flow", "scenario"],
    prompt: "A company shows **rising net income** but **negative operating cash flow**. What's the most likely cause?",
    choices: [
      { id: "a", text: "It is paying too much in dividends" },
      { id: "b", text: "Rapid growth is tying up cash in inventory and receivables faster than profit converts to cash" },
      { id: "c", text: "It has too much cash on hand" },
      { id: "d", text: "Depreciation is too high" },
    ],
    correctId: "b",
    explanation: "Profit is accrual; cash is real. When a company grows fast, **inventory and receivables swell**, tying up cash even as net income rises. The gap shows up as weak or negative CFO — a classic cash crunch.",
  },
  {
    id: "the-cash-flow-statement.q7",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "cash-flow", "scenario"],
    prompt: "A company's FCF dropped sharply this year, but it also built a new plant. What's the soundest interpretation?",
    choices: [
      { id: "a", text: "The business is failing and FCF will stay low forever" },
      { id: "b", text: "A one-time capex spike likely depressed FCF — check whether it recovers next year" },
      { id: "c", text: "Net income must have turned negative" },
      { id: "d", text: "The company is hiding losses" },
    ],
    correctId: "b",
    explanation: "FCF is **lumpy**. A big one-time capex outlay — a new plant — can crush FCF for a year even at a healthy company. The question is whether FCF *recovers* once the spending normalizes.",
  },
  {
    id: "the-cash-flow-statement.q8",
    lessonSlug: "the-cash-flow-statement",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "cash-flow", "misconception"],
    prompt: "Why is it wrong to treat net income as 'the cash the company made'?",
    choices: [
      { id: "a", text: "Net income is always larger than cash" },
      { id: "b", text: "Net income includes non-cash charges and accrual timing; CFO and FCF show the actual cash" },
      { id: "c", text: "Net income excludes all revenue" },
      { id: "d", text: "Net income is only an estimate of the share price" },
    ],
    correctId: "b",
    explanation: "Net income uses accrual accounting — it books uncollected revenue and subtracts non-cash items like depreciation. **CFO and FCF** strip those out to reveal the real cash generated.",
  },
  {
    id: "the-cash-flow-statement.q9",
    lessonSlug: "the-cash-flow-statement",
    type: "numericChoice",
    difficulty: "hard",
    unit: "$",
    tags: ["fundamentals", "cash-flow", "math"],
    prompt: "Net income `$120M`, depreciation `$30M`, receivables rose `$40M`, capex `$50M`. What is free cash flow?",
    choices: [
      { id: "a", text: "$110M", feedback: "That's CFO — capex still needs to be subtracted to reach FCF." },
      { id: "b", text: "$60M" },
      { id: "c", text: "$90M" },
      { id: "d", text: "$120M" },
    ],
    correctId: "b",
    explanation: "`CFO = 120 + 30 − 40 = $110M`. `FCF = CFO − capex = 110 − 50 = $60M` — half the reported net income.",
  },
];
