import type { Question } from "@/lib/quiz/types";

// Quiz for the "The Income Statement, Line by Line" lesson.
export const questions: Question[] = [
  {
    id: "the-income-statement.q1",
    lessonSlug: "the-income-statement",
    type: "numericChoice",
    difficulty: "easy",
    unit: "$",
    tags: ["fundamentals", "income-statement", "math"],
    prompt: "A company has revenue of `$500M` and COGS of `$300M`. What is its gross profit?",
    choices: [
      { id: "a", text: "$200M" },
      { id: "b", text: "$800M", feedback: "That adds the two figures — gross profit subtracts COGS from revenue." },
      { id: "c", text: "$300M" },
      { id: "d", text: "$500M" },
    ],
    correctId: "a",
    explanation: "`Gross profit = revenue − COGS = 500 − 300 = $200M`. It measures core product profitability before operating expenses.",
  },
  {
    id: "the-income-statement.q2",
    lessonSlug: "the-income-statement",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "income-statement"],
    prompt: "Which subtotal **excludes** interest and taxes but **includes** SG&A and R&D?",
    choices: [
      { id: "a", text: "Gross profit", feedback: "Gross profit is computed before SG&A and R&D are subtracted." },
      { id: "b", text: "Operating income (EBIT)" },
      { id: "c", text: "Net income", feedback: "Net income is after interest and taxes." },
      { id: "d", text: "Revenue" },
    ],
    correctId: "b",
    explanation: "**Operating income (EBIT)** = `gross profit − operating expenses` (SG&A, R&D, depreciation), but it sits *before* interest and taxes — the profit from running the business itself.",
  },
  {
    id: "the-income-statement.q3",
    lessonSlug: "the-income-statement",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["fundamentals", "income-statement", "math"],
    prompt: "Gross profit is `$400M`. Operating expenses (SG&A + R&D + depreciation) total `$230M`. What is operating income?",
    choices: [
      { id: "a", text: "$630M", feedback: "That adds the figures — operating income subtracts operating expenses from gross profit." },
      { id: "b", text: "$170M" },
      { id: "c", text: "$230M" },
      { id: "d", text: "$400M" },
    ],
    correctId: "b",
    explanation: "`Operating income = gross profit − operating expenses = 400 − 230 = $170M`.",
  },
  {
    id: "the-income-statement.q4",
    lessonSlug: "the-income-statement",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["fundamentals", "income-statement", "math"],
    prompt: "Operating income is `$170M`, interest is `$20M`, and taxes are `$30M` (no non-operating items). What is net income?",
    choices: [
      { id: "a", text: "$150M", feedback: "That subtracts only interest — taxes still come out." },
      { id: "b", text: "$120M" },
      { id: "c", text: "$140M" },
      { id: "d", text: "$220M" },
    ],
    correctId: "b",
    explanation: "`Net income = operating income − interest − taxes = 170 − 20 − 30 = $120M` — the bottom line that feeds EPS.",
  },
  {
    id: "the-income-statement.q5",
    lessonSlug: "the-income-statement",
    type: "single",
    difficulty: "easy",
    tags: ["fundamentals", "income-statement"],
    prompt: "The income statement is best described as…",
    choices: [
      { id: "a", text: "A snapshot of what the company owns on one day", feedback: "That describes the balance sheet — a snapshot, not a flow." },
      { id: "b", text: "A flow of revenue and costs over a period of time" },
      { id: "c", text: "A list of the company's bank balances" },
      { id: "d", text: "A forecast of next year's earnings" },
    ],
    correctId: "b",
    explanation: "The income statement is a **flow** covering a *period* (a quarter or year) — what came in and went out — not a one-day snapshot like the balance sheet.",
  },
  {
    id: "the-income-statement.q6",
    lessonSlug: "the-income-statement",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "income-statement", "scenario"],
    prompt: "A company's revenue and gross profit are flat year over year, but net income jumped **+40%** — because it sold a warehouse it no longer needed. What's the soundest read?",
    choices: [
      { id: "a", text: "The core business became much more profitable" },
      { id: "b", text: "Most of the jump is a non-operating gain that may not repeat" },
      { id: "c", text: "COGS must have fallen sharply" },
      { id: "d", text: "Revenue was understated" },
    ],
    correctId: "b",
    explanation: "Flat revenue and gross profit mean the *core* business is unchanged. The warehouse sale is a **non-operating, one-time gain** — it inflates net income this period but won't recur. Always check whether profit came from operations.",
  },
  {
    id: "the-income-statement.q7",
    lessonSlug: "the-income-statement",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "income-statement", "scenario"],
    prompt: "Operating income **fell** this year, yet net income **rose**. Which explanation is most consistent with that?",
    choices: [
      { id: "a", text: "Revenue must have doubled" },
      { id: "b", text: "Lower interest or taxes, or a non-operating gain, lifted the bottom line despite weaker operations" },
      { id: "c", text: "COGS rose, which always lifts net income" },
      { id: "d", text: "Gross profit must have been negative" },
    ],
    correctId: "b",
    explanation: "Net income sits *below* operating income. If operations weakened but the bottom line rose, the lift came from below the line — lower taxes or interest, or a one-time non-operating gain — not from the core business.",
  },
  {
    id: "the-income-statement.q8",
    lessonSlug: "the-income-statement",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "income-statement", "misconception"],
    prompt: "Why is it a mistake to assume *higher revenue always means higher profit*?",
    choices: [
      { id: "a", text: "Revenue is always equal to net income" },
      { id: "b", text: "Costs can rise faster than sales, shrinking the subtotals below the top line" },
      { id: "c", text: "Higher revenue lowers the share price" },
      { id: "d", text: "Profit is calculated before revenue" },
    ],
    correctId: "b",
    explanation: "Revenue is just the *top line*. If COGS or operating expenses climb faster than sales, gross, operating, and net profit can all shrink even as revenue grows. Read the subtotals, not just the headline.",
  },
  {
    id: "the-income-statement.q9",
    lessonSlug: "the-income-statement",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["fundamentals", "income-statement", "math"],
    prompt: "Revenue `$1,000M`, COGS `$600M`, SG&A `$150M`, R&D `$50M`, depreciation `$30M`. What is operating income (EBIT)?",
    choices: [
      { id: "a", text: "$400M", feedback: "That's gross profit — operating expenses still need to come out." },
      { id: "b", text: "$170M" },
      { id: "c", text: "$200M" },
      { id: "d", text: "$120M", feedback: "That would be net income, after interest and taxes too." },
    ],
    correctId: "b",
    explanation: "`Gross profit = 1,000 − 600 = 400`. `Operating expenses = 150 + 50 + 30 = 230`. `EBIT = 400 − 230 = $170M`.",
  },
];
