import type { Question } from "@/lib/quiz/types";

// Quiz for the "The Balance Sheet: What a Company Owns and Owes" lesson.
export const questions: Question[] = [
  {
    id: "the-balance-sheet.q1",
    lessonSlug: "the-balance-sheet",
    type: "numericChoice",
    difficulty: "easy",
    unit: "$",
    tags: ["fundamentals", "balance-sheet", "math"],
    prompt: "A company has total assets of `$600M` and total liabilities of `$450M`. What is its shareholders' equity?",
    choices: [
      { id: "a", text: "$1,050M", feedback: "That adds the figures — equity is assets minus liabilities." },
      { id: "b", text: "$150M" },
      { id: "c", text: "$450M" },
      { id: "d", text: "$600M" },
    ],
    correctId: "b",
    explanation: "`Equity = assets − liabilities = 600 − 450 = $150M` — the owners' residual claim, also called book value.",
  },
  {
    id: "the-balance-sheet.q2",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "easy",
    tags: ["fundamentals", "balance-sheet"],
    prompt: "The accounting identity that every balance sheet obeys is…",
    choices: [
      { id: "a", text: "Assets = Liabilities + Equity" },
      { id: "b", text: "Assets = Liabilities − Equity", feedback: "Equity is added to liabilities, not subtracted — the two together fund the assets." },
      { id: "c", text: "Revenue = Costs + Profit" },
      { id: "d", text: "Equity = Assets + Liabilities" },
    ],
    correctId: "a",
    explanation: "**`Assets = Liabilities + Equity`** always balances. Rearranged, `Equity = Assets − Liabilities`.",
  },
  {
    id: "the-balance-sheet.q3",
    lessonSlug: "the-balance-sheet",
    type: "numericChoice",
    difficulty: "medium",
    unit: "x",
    tags: ["fundamentals", "balance-sheet", "math"],
    prompt: "Current assets are `$240M` and current liabilities are `$160M`. What is the current ratio?",
    choices: [
      { id: "a", text: "1.5" },
      { id: "b", text: "0.67", feedback: "That divides the wrong way — current ratio is current assets ÷ current liabilities." },
      { id: "c", text: "80" },
      { id: "d", text: "2.4" },
    ],
    correctId: "a",
    explanation: "`Current ratio = current assets ÷ current liabilities = 240 ÷ 160 = 1.5`. Above 1 means current assets cover near-term obligations.",
  },
  {
    id: "the-balance-sheet.q4",
    lessonSlug: "the-balance-sheet",
    type: "numericChoice",
    difficulty: "medium",
    unit: "$",
    tags: ["fundamentals", "balance-sheet", "math"],
    prompt: "Current assets are `$300M` and current liabilities are `$200M`. What is working capital?",
    choices: [
      { id: "a", text: "$500M", feedback: "Working capital subtracts current liabilities from current assets." },
      { id: "b", text: "$100M" },
      { id: "c", text: "1.5" },
      { id: "d", text: "$200M" },
    ],
    correctId: "b",
    explanation: "`Working capital = current assets − current liabilities = 300 − 200 = $100M` — the cash cushion for the coming year.",
  },
  {
    id: "the-balance-sheet.q5",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "easy",
    tags: ["fundamentals", "balance-sheet"],
    prompt: "The balance sheet is best understood as…",
    choices: [
      { id: "a", text: "A flow of revenue over a quarter" },
      { id: "b", text: "A snapshot of what a company owns and owes on one specific date" },
      { id: "c", text: "A forecast of future cash flows" },
      { id: "d", text: "A record of every transaction in the year" },
    ],
    correctId: "b",
    explanation: "The balance sheet is a **snapshot** at a single date, unlike the income or cash flow statements, which cover a period.",
  },
  {
    id: "the-balance-sheet.q6",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "balance-sheet", "scenario"],
    prompt: "A consistently **profitable** company shows **negative** shareholders' equity. What's the most likely explanation?",
    choices: [
      { id: "a", text: "It must be on the verge of bankruptcy", feedback: "Negative equity can signal distress, but for a profitable firm it often reflects large buybacks instead." },
      { id: "b", text: "Large buybacks and dividends have reduced equity below zero — not necessarily distress" },
      { id: "c", text: "Its assets are worth nothing" },
      { id: "d", text: "The accounting identity has been broken" },
    ],
    correctId: "b",
    explanation: "Equity is roughly retained earnings minus dividends, buybacks, and losses. A profitable firm that aggressively returns cash via **buybacks and dividends** can drive equity negative without being in distress. The identity still balances.",
  },
  {
    id: "the-balance-sheet.q7",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "balance-sheet", "scenario"],
    prompt: "Firm A and Firm B have identical total assets and identical equity. A's debt is mostly long-term; B's debt is mostly current. Which faces more near-term pressure?",
    choices: [
      { id: "a", text: "Firm A, because long-term debt is riskier" },
      { id: "b", text: "Firm B, because more of its obligations come due within 12 months" },
      { id: "c", text: "They are identical in every way" },
      { id: "d", text: "Neither — debt timing doesn't matter" },
    ],
    correctId: "b",
    explanation: "The current vs. long-term split is about *timing*. **Firm B** must repay or refinance more debt within the year, so it faces greater near-term liquidity pressure even though totals match.",
  },
  {
    id: "the-balance-sheet.q8",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "hard",
    tags: ["fundamentals", "balance-sheet", "misconception"],
    prompt: "Why can book value (equity) understate what a company is really worth?",
    choices: [
      { id: "a", text: "It records future profits in advance" },
      { id: "b", text: "Assets are carried at historical cost, so land or a valuable brand may be worth far more" },
      { id: "c", text: "It always excludes cash" },
      { id: "d", text: "Liabilities are double-counted" },
    ],
    correctId: "b",
    explanation: "Book value reflects **historical cost**. Appreciated land or a powerful brand can be worth far more than the sheet shows — while goodwill can cut the other way and *overstate* equity.",
  },
  {
    id: "the-balance-sheet.q9",
    lessonSlug: "the-balance-sheet",
    type: "single",
    difficulty: "medium",
    tags: ["fundamentals", "balance-sheet"],
    prompt: "A company shows total assets of `$800M`, liabilities of `$500M`, and the sheet balances. What does this tell you about its financial health?",
    choices: [
      { id: "a", text: "Nothing about quality — every balance sheet balances, even one loaded with debt" },
      { id: "b", text: "It is definitely a safe, well-run company" },
      { id: "c", text: "It must be unprofitable" },
      { id: "d", text: "Its equity is negative" },
    ],
    correctId: "a",
    explanation: "Balancing is mandatory, not a sign of strength. Here equity is `$300M`, but a heavily indebted firm balances just as neatly — the identity says nothing about *quality*.",
  },
];
