import type { Lesson } from "@/lib/lessons/types";

export const lesson: Lesson = {
  slug: "the-cash-flow-statement",
  title: "The Cash Flow Statement: Why Cash ≠ Profit",
  level: 2,
  moduleId: "markets-fundamental",
  moduleOrder: 3,
  summary: "A profitable company can still run out of cash. Learn the three sections, why net income isn't cash, and how to compute free cash flow.",
  estMinutes: 7,
  sections: [
    {
      type: "text",
      body:
        "Here's a fact that surprises new investors: a company can report rising profits *and* run out of cash at the same time. Profit and cash are not the same thing. The **cash flow statement** exists to show where the actual money went.",
    },
    { type: "heading", text: "Three sections" },
    {
      type: "list",
      items: [
        "**Operating activities (CFO)** — cash from the core business of selling products and services.",
        "**Investing activities** — cash spent or received on long-term assets, including *capital expenditures (capex)*.",
        "**Financing activities** — cash from or to lenders and owners: debt, equity, dividends, and buybacks.",
      ],
    },
    { type: "heading", text: "Why net income isn't cash" },
    {
      type: "text",
      body:
        "Net income is *accrual* accounting. It books revenue when earned (even before the cash arrives), subtracts non-cash charges like depreciation, and ignores the timing of capex. So the cash flow statement *reconciles* it: **CFO starts from net income**, adds back non-cash charges, and adjusts for changes in working capital (like a rise in receivables, which ties up cash).",
    },
    {
      type: "callout",
      tone: "tip",
      body:
        "Rule of thumb: a **non-cash charge** (depreciation) gets *added back* — it reduced profit but no cash left. Cash *tied up* in growing inventory or receivables gets *subtracted* — profit was booked, but the money hasn't arrived.",
    },
    { type: "heading", text: "Free cash flow" },
    {
      type: "text",
      body:
        "The number investors care about most is **free cash flow (FCF)** = `operating cash flow − capex`. It's the cash left over after keeping the business running — the cash genuinely available to pay down debt, fund dividends, or buy back shares.",
    },
    {
      type: "keyTerms",
      terms: [
        { term: "CFO", def: "Cash flow from operations — cash generated by the core business." },
        { term: "Investing activities", def: "Cash used for or from long-term assets, including capex." },
        { term: "Financing activities", def: "Cash flows with lenders and owners: debt, equity, dividends, buybacks." },
        { term: "Capex", def: "Capital expenditures — cash spent on long-term assets like plants and equipment." },
        { term: "Free cash flow (FCF)", def: "`operating cash flow − capex`. Cash available for debt, dividends, or buybacks." },
        { term: "Non-cash charge", def: "An expense that lowers profit but uses no cash, e.g. depreciation." },
        { term: "Working capital change", def: "Cash effect of shifts in receivables, inventory, and payables." },
      ],
    },
    { type: "heading", text: "Worked example" },
    {
      type: "text",
      body:
        "A company reports net income `$120M`, depreciation `$30M`, a `$40M` rise in receivables, and capex `$50M`. Let's build CFO, then FCF.",
    },
    {
      type: "list",
      ordered: true,
      items: [
        "Start from **net income** = `$120M`.",
        "**Add back depreciation** (non-cash): `+$30M`.",
        "**Subtract the receivables increase** (cash tied up): `−$40M`.",
        "**CFO** = `120 + 30 − 40 = $110M`.",
        "**FCF** = `CFO − capex = 110 − 50 = $60M`.",
      ],
    },
    {
      type: "text",
      body:
        "Notice the gap: net income was `$120M`, but free cash flow was only **`$60M`**. Same company, very different stories — and FCF is the one that pays the bills.",
    },
    {
      type: "callout",
      tone: "info",
      body:
        "FCF is *lumpy*. One big capex year — a new factory — can crush FCF temporarily even for a healthy business, so check whether it recovers. And CFO can be flattered short-term by stretching out payables or slashing capex, which isn't sustainable.",
    },
    {
      type: "callout",
      tone: "warn",
      body:
        "Don't read *net income = cash made*. Net income includes non-cash charges and accrual timing. CFO and FCF show the actual cash — that's why a profitable-on-paper company can still run dry when growth ties up cash in inventory and receivables.",
    },
  ],
};
